spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.qq.com
    username: 2279470978@qq.com
    password: abjuamkfsascebff
    default-encoding: utf-8
    protocol: smtps
    port: 465
    # 添加以下配置
    properties:
      mail:
        smtp:
          auth: true  # 需要身份验证
          ssl:
            enable: true  # 启用SSL
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory  # SSL Socket Factory
            fallback: false
          starttls:
            enable: true  # 启用STARTTLS
            required: true

jwt:
  # 签发人
  issuer: zifengliu
  # 秘钥
  secret: TQDGw7oWCy2p5j8267FKCqYamD3bzhjbx0TPp7LwYpLwKSEFxqvTizminm8qUD0fm2rVY0xtAKaF7BZ9NZANmQ==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer


